/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/jp48yFYF1WU
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button";

export function AddProduct() {
  return (
    <div className="bg-white rounded-lg shadow-lg overflow-hidden w-full max-w-sm m-auto">
      <div className="aspect-[4/3] bg-gray-100 overflow-hidden">
        <img
          alt="Product Image"
          className="w-full h-full object-cover"
          height="400"
          src="/placeholder.svg"
          style={{
            aspectRatio: "600/400",
            objectFit: "cover",
          }}
          width="600"
        />
      </div>
      <div className="p-6 space-y-4 text-black">
        <h3 className="text-xl font-bold">Minimalist Ceramic Vase</h3>
        <p className="text-gray-500 text-sm">
          A beautifully crafted ceramic vase that adds a touch of elegance to
          any space. A beautifully crafted ceramic vase that adds a touch of
          elegance to any space. A beautifully crafted ceramic vase that adds a
          touch of elegance to any space. A beautifully crafted ceramic vase
          that adds a touch of elegance to any space. A beautifully crafted
          ceramic vase that adds a touch of elegance to any space. A beautifully
          crafted ceramic vase that adds a touch of elegance to any space. A
          beautifully crafted ceramic vase that adds a touch of elegance to any
          space. A beautifully crafted ceramic vase that adds a touch of
          elegance to any space. A beautifully crafted ceramic vase that adds a
          touch of elegance to any space. A beautifully crafted ceramic vase
          that adds a touch of elegance to any space. A beautifully crafted
          ceramic vase that adds a touch of elegance to any space. A beautifully
          crafted ceramic vase that adds a touch of elegance to any space.
        </p>
        <div className="border">
          {" "}
          #car #car #car #car #car #car #car #car #car #car #car #car
        </div>
        <div className="flex text-black items-center justify-between">
          <span className="text-2xl font-bold">$49.99</span>
          <Button className="border" size="sm">
            Add to Shop
          </Button>
        </div>
      </div>
    </div>
  );
}
