/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/zUhyjRmhUxa
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
'use client'
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { CardContent, CardFooter, Card } from "@/components/ui/card"
import Link from "next/link"
import { useState } from "react"
export function Login() {
  const [isLoggedIn, setIsLoggedIn] = useState(true)
  return (
    <div className="flex min-h-[100dvh] items-center justify-center bg-gray-100 px-4 dark:bg-gray-950 p-2">
      <div className="w-full max-w-md space-y-6 p-2">
        <div className="text-center">
          <h1 className="text-3xl font-bold">Welcome back</h1>
        </div>
        {!isLoggedIn && <Card>
          <CardContent className="space-y-4 m-4">
          <p className="text-gray-500 dark:text-gray-400">Enter your Phone to access your account.</p>
            <div className="grid gap-2 m-auto">
              <Label htmlFor="email-phone">Phone No</Label>
              <Input id="email-phone" placeholder="Enter ......" />
              <Button className="w-full">Get Otp</Button>
            </div>
            <div className="grid gap-2 m-auto">
              <Label htmlFor="Otp">Otp</Label>
              <Input id="Otp" placeholder="Enter your Otp" type="password" />
              <Button className="w-full">Login</Button>
            </div>
          </CardContent>
        </Card>}
        {isLoggedIn && <Link href='/home' className="w-full max-w-md space-y-6 p-2">
          6203134277
          <Button className="w-full">Home</Button>
          </Link>
          }
      </div>

    </div>
  )
}

function SwitchCameraIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M11 19H4a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2h5" />
      <path d="M13 5h7a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-5" />
      <circle cx="12" cy="12" r="3" />
      <path d="m18 22-3-3 3-3" />
      <path d="m6 2 3 3-3 3" />
    </svg>
  )
}
